---
- name: install letsencrypt
  apt:
    name: letsencrypt
    state: latest
  tags: ssl

- name: Kerio-connect stoping
  service:
    name: kerio-connect
    state: stopped


- name: Create letsencrypt certificate
  shell: certbot certonly --standalone --expand --keep-until-expiring {{ lets_dry_run }} -m {{ lets_letsencrypt_email }} --agree-tos -d {{ item.server_name }}
  args:
    creates: "{{ lets_deploy_certpath }}/{{ item.server_name }}"
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') != 'absent'

- name: Revoke letsencrypt certificate
  shell: certbot {{ lets_dry_run }} revoke --standalone -d "{{ item.server_name }}" --cert-path "{{ lets_install_path }}/{{ item.server_name }}/cert1.pem"
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') == 'absent'

- name: Delete letsencrypt certificate
  shell: certbot {{ lets_dry_run }} delete --cert-name "{{ item.server_name }}"
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') == 'absent'

- name: Add letsencrypt job for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: "{{ lets_monthly }}"
    job: "service kerio-connect stop && certbot renew && service kerio-connect start"
  when: lets_crontab_enable == 'enable'

- name: Remove letsencrypt job for cert renewal
  cron:
    name: letsencrypt_renewal
    state: absent
  when: lets_crontab_enable == 'disable'

- name: Add link from letsencrypt to kerio-connect.crt
  file:
    src: "/etc/letsencrypt/live/{{ item.server_name }}/fullchain.pem"
    dest: "{{ lets_deploy_certpath }}/{{ item.server_name }}.crt"
    state: link
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') != 'absent' and lets_dry_run != "--dry-run"

- name: Add link from letsencrypt to kerio-connect.key
  file:
    src: "/etc/letsencrypt/live/{{ item.server_name }}/privkey.pem"
    dest: "{{ lets_deploy_certpath }}/{{ item.server_name }}.key"
    state: link
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') != 'absent' and lets_dry_run != "--dry-run"

- name: Remove link from letsencrypt to kerio-connect.crt
  file:
    path: "{{ lets_deploy_certpath }}/{{ item.server_name }}.crt"
    state: absent
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') == 'absent' and lets_dry_run != "--dry-run"

- name: Remove link from letsencrypt to kerio-connect.key
  file:
    path: "{{ lets_deploy_certpath }}/{{ item.server_name }}.key"
    state: absent
  with_items: "{{ lets_deploy_vhosts }}"
  when: item.state|default('present') == 'absent' and lets_dry_run != "--dry-run"

- name: Kerio-connect starting
  service:
    name: kerio-connect
    state: started
